import { load } from 'cheerio'
import prettier from 'prettier'
import {
  basicKebabCase,
  convertFromPercentage,
  localizedTitleCase,
  replaceDiacritics,
  writeFile,
} from './utils'
import { rawHtmlTables } from './data/raw-html-tables'

type PlaceTaxesRecord = {
  jedinica: string
  nizaStopa: number
  visaStopa: number
}

function generateTaxRecords() {
  const taxRateRecords: PlaceTaxesRecord[] = []

  const rows = rawHtmlTables
    .map((table) => {
      const $ = load(table)
      const rows = $('table table tbody td')
        .get()
        .map((td) => $(td).text())

      return rows
    })
    .flat()

  for (let i = 0; i < rows.length; i += 3) {
    const jedinica = rows[i]

    taxRateRecords.push({
      jedinica: localizedTitleCase(jedinica),
      nizaStopa: convertFromPercentage(rows[i + 1]),
      visaStopa: convertFromPercentage(rows[i + 2]),
    })
  }

  return taxRateRecords
}

async function writeTaxRecords(taxRecords: PlaceTaxesRecord[]) {
  const written = await writeFile(
    'src/data/places.json',
    JSON.stringify(taxRecords, null, 2),
  )

  if (written) {
    console.log('✅ Tax rates written to "/src/data/places.json"')
  } else {
    console.error('❌ Error writing tax rates file')
  }
}
async function writeGeneratedCode(content: string) {
  const written = await writeFile('src/data/places.ts', content)
  if (written) {
    console.log(
      '✅ Places code generated and written to "/src/data/places.ts"',
    )
  } else {
    console.error('❌ Error writing places type file')
  }
}

const taxRecords = generateTaxRecords()
const placeNames = taxRecords.map((record) => record.jedinica)

const PlaceMap = taxRecords.reduce(
  (acc, record) => {
    const { jedinica, visaStopa, nizaStopa } = record
    const key = basicKebabCase(replaceDiacritics(jedinica))
    acc[key] = {
      name: jedinica,
      taxRateLow: nizaStopa,
      taxRateHigh: visaStopa,
    }
    return acc
  },
  {} as Record<string, { name: string, taxRateLow: number, taxRateHigh: number }>,
)

const places = Object.keys(PlaceMap)

async function generateCode() {
  const comment = `
    // This file was generated by the "gen-tax-rates.ts" script. 
    // Do not modify it manually.
  `

  const PlaceMapCode = `
    /**
     * Tax rates for different places in Croatia.
     * Generated off of the data from 'porezi.json'.
    */
    export const PlaceMap = ${JSON.stringify(PlaceMap, null, 2)} as const
  `

  const PlaceCode = `export type Place = keyof typeof PlaceMap`

  const PlacesCode = `export const places: Place[] = ${JSON.stringify(places, null, 2)} as const`

  const PlaceTypeCode = `
    /**
     * Type for all places in 'porezi.json'.
    */
    export type PlaceName = ${placeNames.map((place) => `| '${place}'`).join(' ')}
  `

  const content = `${comment}\n\n${PlaceMapCode}\n\n${PlaceCode}\n\n${PlacesCode}\n\n${PlaceTypeCode}`

  const formattedCode = await prettier.format(content, { parser: 'typescript' })

  return formattedCode
}

await writeTaxRecords(taxRecords)

await writeGeneratedCode(await generateCode())
