// This file was generated by "gen-tax-rates.ts".

/**
 * Tax rates for different places in Croatia.
 * Data source: "https://isplate.info/porez-na-dohodak-porezne-stope.aspx" → serialized to "places.json".
 */

export const PlaceMap = {
  'brodski-stupnik': {
    name: 'Brodski Stupnik',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'klenovnik': {
    name: 'Klenovnik',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'nin': {
    name: 'Nin',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'novigrad-cittanova': {
    name: 'Novigrad-Cittanova',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'podgora': {
    name: 'Podgora',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'vrbanja': {
    name: 'Vrbanja',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'andrijasevci': {
    name: 'Andrijaševci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'bale-valle': {
    name: 'Bale-Valle',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'barban': {
    name: 'Barban',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'bebrina': {
    name: 'Bebrina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'bednja': {
    name: 'Bednja',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'brtonigla-verteneglio': {
    name: 'Brtonigla-Verteneglio',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'caglin': {
    name: 'Čaglin',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ceminac': {
    name: 'Čeminac',
    taxRateLow: 0.2,
    taxRateHigh: 0.25,
  },
  'cepin': {
    name: 'Čepin',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'donji-lapac': {
    name: 'Donji Lapac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'dugi-rat': {
    name: 'Dugi Rat',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'dvor': {
    name: 'Dvor',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'fuzine': {
    name: 'Fužine',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'gradina': {
    name: 'Gradina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'gunja': {
    name: 'Gunja',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'hlebine': {
    name: 'Hlebine',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'jaksic': {
    name: 'Jakšić',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'jelsa': {
    name: 'Jelsa',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'kamanje': {
    name: 'Kamanje',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'karojba': {
    name: 'Karojba',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'krnjak': {
    name: 'Krnjak',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'liznjan-lisignano': {
    name: 'Ližnjan-Lisignano',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lokvicici': {
    name: 'Lokvičići',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'luka': {
    name: 'Luka',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lumbarda': {
    name: 'Lumbarda',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'marijanci': {
    name: 'Marijanci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'medulin': {
    name: 'Medulin',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'nova-kapela': {
    name: 'Nova Kapela',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'novigrad': {
    name: 'Novigrad',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'orebic': {
    name: 'Orebić',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'orle': {
    name: 'Orle',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'peteranec': {
    name: 'Peteranec',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'plitvicka-jezera': {
    name: 'Plitvička Jezera',
    taxRateLow: 0.21,
    taxRateHigh: 0.33,
  },
  'posedarje': {
    name: 'Posedarje',
    taxRateLow: 0.18,
    taxRateHigh: 0.32,
  },
  'privlaka-zadar': {
    name: 'Privlaka (Zadar)',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'radoboj': {
    name: 'Radoboj',
    taxRateLow: 0.22,
    taxRateHigh: 0.32,
  },
  'ribnik': {
    name: 'Ribnik',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'stara-gradiska': {
    name: 'Stara Gradiška',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ston': {
    name: 'Ston',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'suhopolje': {
    name: 'Suhopolje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sutivan': {
    name: 'Sutivan',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'sveti-ilija': {
    name: 'Sveti Ilija',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sveti-kriz-zacretje': {
    name: 'Sveti Križ Začretje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sveti-petar-u-sumi': {
    name: 'Sveti Petar u Šumi',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sodolovci': {
    name: 'Šodolovci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'tordinci': {
    name: 'Tordinci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'tucepi': {
    name: 'Tučepi',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'vojnic': {
    name: 'Vojnić',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'imotski': {
    name: 'Imotski',
    taxRateLow: 0.2,
    taxRateHigh: 0.25,
  },
  'komiza': {
    name: 'Komiža',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'krizevci': {
    name: 'Križevci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'makarska': {
    name: 'Makarska',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'novi-marof': {
    name: 'Novi Marof',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'pozega': {
    name: 'Požega',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'petrinja': {
    name: 'Petrinja',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zagreb': {
    name: 'Zagreb',
    taxRateLow: 0.23,
    taxRateHigh: 0.35,
  },
  'cadavica': {
    name: 'Čađavica',
    taxRateLow: 0.2,
    taxRateHigh: 0.25,
  },
  'draganic': {
    name: 'Draganić',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'duga-resa': {
    name: 'Duga Resa',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'gornji-bogicevci': {
    name: 'Gornji Bogićevci',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'gospic': {
    name: 'Gospić',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'klakar': {
    name: 'Klakar',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'milna': {
    name: 'Milna',
    taxRateLow: 0.21,
    taxRateHigh: 0.33,
  },
  'mrkopalj': {
    name: 'Mrkopalj',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ogulin': {
    name: 'Ogulin',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'omis': {
    name: 'Omiš',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'pula-pola': {
    name: 'Pula-Pola',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'stari-mikanovci': {
    name: 'Stari Mikanovci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sveti-ivan-zelina': {
    name: 'Sveti Ivan Zelina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sveti-lovrec': {
    name: 'Sveti Lovreč',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'udbina': {
    name: 'Udbina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vrgorac': {
    name: 'Vrgorac',
    taxRateLow: 0.22,
    taxRateHigh: 0.25,
  },
  'vuka': {
    name: 'Vuka',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zdenci': {
    name: 'Zdenci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zakanje': {
    name: 'Žakanje',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'antunovac': {
    name: 'Antunovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'beretinec': {
    name: 'Beretinec',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'biskupija': {
    name: 'Biskupija',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'bol': {
    name: 'Bol',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'darda': {
    name: 'Darda',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'drenovci': {
    name: 'Drenovci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'dugo-selo': {
    name: 'Dugo Selo',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'erdut': {
    name: 'Erdut',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'hrvace': {
    name: 'Hrvace',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'klis': {
    name: 'Klis',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'lanisce': {
    name: 'Lanišće',
    taxRateLow: 0.21,
    taxRateHigh: 0.3,
  },
  'lastovo': {
    name: 'Lastovo',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'mali-bukovec': {
    name: 'Mali Bukovec',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'matulji': {
    name: 'Matulji',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'mihovljan': {
    name: 'Mihovljan',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'podcrkavlje': {
    name: 'Podcrkavlje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'pokupsko': {
    name: 'Pokupsko',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'policnik': {
    name: 'Poličnik',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'pregrada': {
    name: 'Pregrada',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'rasa': {
    name: 'Raša',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'rovisce': {
    name: 'Rovišće',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ruzic': {
    name: 'Ružić',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'stari-jankovci': {
    name: 'Stari Jankovci',
    taxRateLow: 0.15,
    taxRateHigh: 0.25,
  },
  'trogir': {
    name: 'Trogir',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'viskovo': {
    name: 'Viškovo',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vodinci': {
    name: 'Vođinci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zminj': {
    name: 'Žminj',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'kastav': {
    name: 'Kastav',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'otocac': {
    name: 'Otočac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'rijeka': {
    name: 'Rijeka',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'sinj': {
    name: 'Sinj',
    taxRateLow: 0.18,
    taxRateHigh: 0.3,
  },
  'sisak': {
    name: 'Sisak',
    taxRateLow: 0.23,
    taxRateHigh: 0.34,
  },
  'slunj': {
    name: 'Slunj',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'virovitica': {
    name: 'Virovitica',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zupanja': {
    name: 'Županja',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'babina-greda': {
    name: 'Babina Greda',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'baska-voda': {
    name: 'Baška Voda',
    taxRateLow: 0.17,
    taxRateHigh: 0.27,
  },
  'bedenica': {
    name: 'Bedenica',
    taxRateLow: 0.21,
    taxRateHigh: 0.3,
  },
  'bilje': {
    name: 'Bilje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'borovo': {
    name: 'Borovo',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'donja-voca': {
    name: 'Donja Voća',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'drenje': {
    name: 'Drenje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'drnis': {
    name: 'Drniš',
    taxRateLow: 0.2,
    taxRateHigh: 0.25,
  },
  'durđenovac': {
    name: 'Đurđenovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'groznjan-grisignana': {
    name: 'Grožnjan-Grisignana',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'hercegovac': {
    name: 'Hercegovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'koncanica': {
    name: 'Končanica',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'lisane-ostrovicke': {
    name: 'Lišane Ostrovičke',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'martijanec': {
    name: 'Martijanec',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'semeljci': {
    name: 'Semeljci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sibinj': {
    name: 'Sibinj',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'veliki-grdevac': {
    name: 'Veliki Grđevac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vizinada-visinada': {
    name: 'Vižinada-Visinada',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zumberak': {
    name: 'Žumberak',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'zupa-dubrovacka': {
    name: 'Župa Dubrovačka',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'beli-manastir': {
    name: 'Beli Manastir',
    taxRateLow: 0.2,
    taxRateHigh: 0.25,
  },
  'cabar': {
    name: 'Čabar',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'nova-gradiska': {
    name: 'Nova Gradiška',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'split': {
    name: 'Split',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'sveta-nedelja-samobor': {
    name: 'Sveta Nedelja (Samobor)',
    taxRateLow: 0.18,
    taxRateHigh: 0.28,
  },
  'varazdinske-toplice': {
    name: 'Varaždinske Toplice',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'brckovljani': {
    name: 'Brckovljani',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'brinje': {
    name: 'Brinje',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'cerna': {
    name: 'Cerna',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'dezanovac': {
    name: 'Dežanovac',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'dragalic': {
    name: 'Dragalić',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'kanfanar': {
    name: 'Kanfanar',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'kapela': {
    name: 'Kapela',
    taxRateLow: 0.15,
    taxRateHigh: 0.25,
  },
  'krapina': {
    name: 'Krapina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lasinja': {
    name: 'Lasinja',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'lobor': {
    name: 'Lobor',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lupoglav': {
    name: 'Lupoglav',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'marija-gorica': {
    name: 'Marija Gorica',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'markusica': {
    name: 'Markušica',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'marusevec': {
    name: 'Maruševec',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'negoslavci': {
    name: 'Negoslavci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'oprtalj-portole': {
    name: 'Oprtalj-Portole',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'perusic': {
    name: 'Perušić',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'punat': {
    name: 'Punat',
    taxRateLow: 0.15,
    taxRateHigh: 0.3,
  },
  'sirac': {
    name: 'Sirač',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sopje': {
    name: 'Sopje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'sracinec': {
    name: 'Sračinec',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'starigrad': {
    name: 'Starigrad',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'tribunj': {
    name: 'Tribunj',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'trnovec-bartolovecki': {
    name: 'Trnovec Bartolovečki',
    taxRateLow: 0.22,
    taxRateHigh: 0.32,
  },
  'velika': {
    name: 'Velika',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'visoko': {
    name: 'Visoko',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vladislavci': {
    name: 'Vladislavci',
    taxRateLow: 0.2,
    taxRateHigh: 0.25,
  },
  'vrbje': {
    name: 'Vrbje',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'vrsi': {
    name: 'Vrsi',
    taxRateLow: 0.15,
    taxRateHigh: 0.3,
  },
  'buje-buie': {
    name: 'Buje-Buie',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'donja-stubica': {
    name: 'Donja Stubica',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'donji-andrijevci': {
    name: 'Donji Andrijevci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'glina': {
    name: 'Glina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ilok': {
    name: 'Ilok',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'jastrebarsko': {
    name: 'Jastrebarsko',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'karlovac': {
    name: 'Karlovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'novi-vinodolski': {
    name: 'Novi Vinodolski',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'novska': {
    name: 'Novska',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ozalj': {
    name: 'Ozalj',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'pag': {
    name: 'Pag',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'pakrac': {
    name: 'Pakrac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'samobor': {
    name: 'Samobor',
    taxRateLow: 0.18,
    taxRateHigh: 0.27,
  },
  'stari-grad': {
    name: 'Stari Grad',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'valpovo': {
    name: 'Valpovo',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'varazdin': {
    name: 'Varaždin',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'vodnjan-dignano': {
    name: 'Vodnjan-Dignano',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'vrbovsko': {
    name: 'Vrbovsko',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'vrlika': {
    name: 'Vrlika',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'belisce': {
    name: 'Belišće',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'brdovec': {
    name: 'Brdovec',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'cačinci': {
    name: 'Čačinci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'gorican': {
    name: 'Goričan',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'gradac': {
    name: 'Gradac',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'kravarsko': {
    name: 'Kravarsko',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lipik': {
    name: 'Lipik',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'magadenovac': {
    name: 'Magadenovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'okrug': {
    name: 'Okrug',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'petrijanec': {
    name: 'Petrijanec',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'ploce': {
    name: 'Ploče',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'primosten': {
    name: 'Primošten',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'tisno': {
    name: 'Tisno',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'velika-kopanica': {
    name: 'Velika Kopanica',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vrhovine': {
    name: 'Vrhovine',
    taxRateLow: 0.18,
    taxRateHigh: 0.3,
  },
  'buzet': {
    name: 'Buzet',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'daruvar': {
    name: 'Daruvar',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ivanec': {
    name: 'Ivanec',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'knin': {
    name: 'Knin',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'bizovac': {
    name: 'Bizovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ernestinovo': {
    name: 'Ernestinovo',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'kaptol': {
    name: 'Kaptol',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lepoglava': {
    name: 'Lepoglava',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'lukac': {
    name: 'Lukač',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'dicmo': {
    name: 'Dicmo',
    taxRateLow: 0.21,
    taxRateHigh: 0.32,
  },
  'grubisno-polje': {
    name: 'Grubišno Polje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'klinca-sela': {
    name: 'Klinča Sela',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'lekenik': {
    name: 'Lekenik',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'supetar': {
    name: 'Supetar',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'baska': {
    name: 'Baška',
    taxRateLow: 0.15,
    taxRateHigh: 0.25,
  },
  'bilice': {
    name: 'Bilice',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'bjelovar': {
    name: 'Bjelovar',
    taxRateLow: 0.18,
    taxRateHigh: 0.28,
  },
  'breznica': {
    name: 'Breznica',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'jasenovac': {
    name: 'Jasenovac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'ludbreg': {
    name: 'Ludbreg',
    taxRateLow: 0.21,
    taxRateHigh: 0.33,
  },
  'pazin': {
    name: 'Pazin',
    taxRateLow: 0.22,
    taxRateHigh: 0.3,
  },
  'stitar': {
    name: 'Štitar',
    taxRateLow: 0.2,
    taxRateHigh: 0.33,
  },
  'tar-vabriga-torre-abrega': {
    name: 'Tar-Vabriga-Torre-Abrega',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'veliki-bukovec': {
    name: 'Veliki Bukovec',
    taxRateLow: 0.21,
    taxRateHigh: 0.33,
  },
  'kijevo': {
    name: 'Kijevo',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'mljet': {
    name: 'Mljet',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'resetari': {
    name: 'Rešetari',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'veliko-trojstvo': {
    name: 'Veliko Trojstvo',
    taxRateLow: 0.17,
    taxRateHigh: 0.27,
  },
  'crnac': {
    name: 'Crnac',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'molve': {
    name: 'Molve',
    taxRateLow: 0.15,
    taxRateHigh: 0.25,
  },
  'veliko-trgovisce': {
    name: 'Veliko Trgovišće',
    taxRateLow: 0.22,
    taxRateHigh: 0.33,
  },
  'vinica': {
    name: 'Vinica',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'gracisce': {
    name: 'Gračišće',
    taxRateLow: 0.21,
    taxRateHigh: 0.31,
  },
  'stankovci': {
    name: 'Stankovci',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'trpanj': {
    name: 'Trpanj',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vidovec': {
    name: 'Vidovec',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'hrascina': {
    name: 'Hrašćina',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'severin': {
    name: 'Severin',
    taxRateLow: 0.18,
    taxRateHigh: 0.28,
  },
  'pitomaca': {
    name: 'Pitomača',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'vodice': {
    name: 'Vodice',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
  'oroslavje': {
    name: 'Oroslavje',
    taxRateLow: 0.2,
    taxRateHigh: 0.3,
  },
} as const

export type Place = keyof typeof PlaceMap

export const places: Place[] = [
  'brodski-stupnik',
  'klenovnik',
  'nin',
  'novigrad-cittanova',
  'podgora',
  'vrbanja',
  'andrijasevci',
  'bale-valle',
  'barban',
  'bebrina',
  'bednja',
  'brtonigla-verteneglio',
  'caglin',
  'ceminac',
  'cepin',
  'donji-lapac',
  'dugi-rat',
  'dvor',
  'fuzine',
  'gradina',
  'gunja',
  'hlebine',
  'jaksic',
  'jelsa',
  'kamanje',
  'karojba',
  'krnjak',
  'liznjan-lisignano',
  'lokvicici',
  'luka',
  'lumbarda',
  'marijanci',
  'medulin',
  'nova-kapela',
  'novigrad',
  'orebic',
  'orle',
  'peteranec',
  'plitvicka-jezera',
  'posedarje',
  'privlaka-zadar',
  'radoboj',
  'ribnik',
  'stara-gradiska',
  'ston',
  'suhopolje',
  'sutivan',
  'sveti-ilija',
  'sveti-kriz-zacretje',
  'sveti-petar-u-sumi',
  'sodolovci',
  'tordinci',
  'tucepi',
  'vojnic',
  'imotski',
  'komiza',
  'krizevci',
  'makarska',
  'novi-marof',
  'pozega',
  'petrinja',
  'zagreb',
  'cadavica',
  'draganic',
  'duga-resa',
  'gornji-bogicevci',
  'gospic',
  'klakar',
  'milna',
  'mrkopalj',
  'ogulin',
  'omis',
  'pula-pola',
  'stari-mikanovci',
  'sveti-ivan-zelina',
  'sveti-lovrec',
  'udbina',
  'vrgorac',
  'vuka',
  'zdenci',
  'zakanje',
  'antunovac',
  'beretinec',
  'biskupija',
  'bol',
  'darda',
  'drenovci',
  'dugo-selo',
  'erdut',
  'hrvace',
  'klis',
  'lanisce',
  'lastovo',
  'mali-bukovec',
  'matulji',
  'mihovljan',
  'podcrkavlje',
  'pokupsko',
  'policnik',
  'pregrada',
  'rasa',
  'rovisce',
  'ruzic',
  'stari-jankovci',
  'trogir',
  'viskovo',
  'vodinci',
  'zminj',
  'kastav',
  'otocac',
  'rijeka',
  'sinj',
  'sisak',
  'slunj',
  'virovitica',
  'zupanja',
  'babina-greda',
  'baska-voda',
  'bedenica',
  'bilje',
  'borovo',
  'donja-voca',
  'drenje',
  'drnis',
  'durđenovac',
  'groznjan-grisignana',
  'hercegovac',
  'koncanica',
  'lisane-ostrovicke',
  'martijanec',
  'semeljci',
  'sibinj',
  'veliki-grdevac',
  'vizinada-visinada',
  'zumberak',
  'zupa-dubrovacka',
  'beli-manastir',
  'cabar',
  'nova-gradiska',
  'split',
  'sveta-nedelja-samobor',
  'varazdinske-toplice',
  'brckovljani',
  'brinje',
  'cerna',
  'dezanovac',
  'dragalic',
  'kanfanar',
  'kapela',
  'krapina',
  'lasinja',
  'lobor',
  'lupoglav',
  'marija-gorica',
  'markusica',
  'marusevec',
  'negoslavci',
  'oprtalj-portole',
  'perusic',
  'punat',
  'sirac',
  'sopje',
  'sracinec',
  'starigrad',
  'tribunj',
  'trnovec-bartolovecki',
  'velika',
  'visoko',
  'vladislavci',
  'vrbje',
  'vrsi',
  'buje-buie',
  'donja-stubica',
  'donji-andrijevci',
  'glina',
  'ilok',
  'jastrebarsko',
  'karlovac',
  'novi-vinodolski',
  'novska',
  'ozalj',
  'pag',
  'pakrac',
  'samobor',
  'stari-grad',
  'valpovo',
  'varazdin',
  'vodnjan-dignano',
  'vrbovsko',
  'vrlika',
  'belisce',
  'brdovec',
  'cačinci',
  'gorican',
  'gradac',
  'kravarsko',
  'lipik',
  'magadenovac',
  'okrug',
  'petrijanec',
  'ploce',
  'primosten',
  'tisno',
  'velika-kopanica',
  'vrhovine',
  'buzet',
  'daruvar',
  'ivanec',
  'knin',
  'bizovac',
  'ernestinovo',
  'kaptol',
  'lepoglava',
  'lukac',
  'dicmo',
  'grubisno-polje',
  'klinca-sela',
  'lekenik',
  'supetar',
  'baska',
  'bilice',
  'bjelovar',
  'breznica',
  'jasenovac',
  'ludbreg',
  'pazin',
  'stitar',
  'tar-vabriga-torre-abrega',
  'veliki-bukovec',
  'kijevo',
  'mljet',
  'resetari',
  'veliko-trojstvo',
  'crnac',
  'molve',
  'veliko-trgovisce',
  'vinica',
  'gracisce',
  'stankovci',
  'trpanj',
  'vidovec',
  'hrascina',
  'severin',
  'pitomaca',
  'vodice',
  'oroslavje',
] as const

export type PlaceName =
  | 'Brodski Stupnik'
  | 'Klenovnik'
  | 'Nin'
  | 'Novigrad-Cittanova'
  | 'Podgora'
  | 'Vrbanja'
  | 'Andrijaševci'
  | 'Bale-Valle'
  | 'Barban'
  | 'Bebrina'
  | 'Bednja'
  | 'Brtonigla-Verteneglio'
  | 'Čaglin'
  | 'Čeminac'
  | 'Čepin'
  | 'Donji Lapac'
  | 'Dugi Rat'
  | 'Dvor'
  | 'Fužine'
  | 'Gradina'
  | 'Gunja'
  | 'Hlebine'
  | 'Jakšić'
  | 'Jelsa'
  | 'Kamanje'
  | 'Karojba'
  | 'Krnjak'
  | 'Ližnjan-Lisignano'
  | 'Lokvičići'
  | 'Luka'
  | 'Lumbarda'
  | 'Marijanci'
  | 'Medulin'
  | 'Nova Kapela'
  | 'Novigrad'
  | 'Orebić'
  | 'Orle'
  | 'Peteranec'
  | 'Plitvička Jezera'
  | 'Posedarje'
  | 'Privlaka (Zadar)'
  | 'Radoboj'
  | 'Ribnik'
  | 'Stara Gradiška'
  | 'Ston'
  | 'Suhopolje'
  | 'Sutivan'
  | 'Sveti Ilija'
  | 'Sveti Križ Začretje'
  | 'Sveti Petar u Šumi'
  | 'Šodolovci'
  | 'Tordinci'
  | 'Tučepi'
  | 'Vojnić'
  | 'Imotski'
  | 'Komiža'
  | 'Križevci'
  | 'Makarska'
  | 'Novi Marof'
  | 'Požega'
  | 'Petrinja'
  | 'Zagreb'
  | 'Čađavica'
  | 'Draganić'
  | 'Duga Resa'
  | 'Gornji Bogićevci'
  | 'Gospić'
  | 'Klakar'
  | 'Milna'
  | 'Mrkopalj'
  | 'Ogulin'
  | 'Omiš'
  | 'Pula-Pola'
  | 'Stari Mikanovci'
  | 'Sveti Ivan Zelina'
  | 'Sveti Lovreč'
  | 'Udbina'
  | 'Vrgorac'
  | 'Vuka'
  | 'Zdenci'
  | 'Žakanje'
  | 'Antunovac'
  | 'Beretinec'
  | 'Biskupija'
  | 'Bol'
  | 'Darda'
  | 'Drenovci'
  | 'Dugo Selo'
  | 'Erdut'
  | 'Hrvace'
  | 'Klis'
  | 'Lanišće'
  | 'Lastovo'
  | 'Mali Bukovec'
  | 'Matulji'
  | 'Mihovljan'
  | 'Podcrkavlje'
  | 'Pokupsko'
  | 'Poličnik'
  | 'Pregrada'
  | 'Raša'
  | 'Rovišće'
  | 'Ružić'
  | 'Stari Jankovci'
  | 'Trogir'
  | 'Viškovo'
  | 'Vođinci'
  | 'Žminj'
  | 'Kastav'
  | 'Otočac'
  | 'Rijeka'
  | 'Sinj'
  | 'Sisak'
  | 'Slunj'
  | 'Virovitica'
  | 'Županja'
  | 'Babina Greda'
  | 'Baška Voda'
  | 'Bedenica'
  | 'Bilje'
  | 'Borovo'
  | 'Donja Voća'
  | 'Drenje'
  | 'Drniš'
  | 'Đurđenovac'
  | 'Grožnjan-Grisignana'
  | 'Hercegovac'
  | 'Končanica'
  | 'Lišane Ostrovičke'
  | 'Martijanec'
  | 'Semeljci'
  | 'Sibinj'
  | 'Veliki Grđevac'
  | 'Vižinada-Visinada'
  | 'Žumberak'
  | 'Župa Dubrovačka'
  | 'Beli Manastir'
  | 'Čabar'
  | 'Nova Gradiška'
  | 'Split'
  | 'Sveta Nedelja (Samobor)'
  | 'Varaždinske Toplice'
  | 'Brckovljani'
  | 'Brinje'
  | 'Cerna'
  | 'Dežanovac'
  | 'Dragalić'
  | 'Kanfanar'
  | 'Kapela'
  | 'Krapina'
  | 'Lasinja'
  | 'Lobor'
  | 'Lupoglav'
  | 'Marija Gorica'
  | 'Markušica'
  | 'Maruševec'
  | 'Negoslavci'
  | 'Oprtalj-Portole'
  | 'Perušić'
  | 'Punat'
  | 'Sirač'
  | 'Sopje'
  | 'Sračinec'
  | 'Starigrad'
  | 'Tribunj'
  | 'Trnovec Bartolovečki'
  | 'Velika'
  | 'Visoko'
  | 'Vladislavci'
  | 'Vrbje'
  | 'Vrsi'
  | 'Buje-Buie'
  | 'Donja Stubica'
  | 'Donji Andrijevci'
  | 'Glina'
  | 'Ilok'
  | 'Jastrebarsko'
  | 'Karlovac'
  | 'Novi Vinodolski'
  | 'Novska'
  | 'Ozalj'
  | 'Pag'
  | 'Pakrac'
  | 'Samobor'
  | 'Stari Grad'
  | 'Valpovo'
  | 'Varaždin'
  | 'Vodnjan-Dignano'
  | 'Vrbovsko'
  | 'Vrlika'
  | 'Belišće'
  | 'Brdovec'
  | 'Čačinci'
  | 'Goričan'
  | 'Gradac'
  | 'Kravarsko'
  | 'Lipik'
  | 'Magadenovac'
  | 'Okrug'
  | 'Petrijanec'
  | 'Ploče'
  | 'Primošten'
  | 'Tisno'
  | 'Velika Kopanica'
  | 'Vrhovine'
  | 'Buzet'
  | 'Daruvar'
  | 'Ivanec'
  | 'Knin'
  | 'Bizovac'
  | 'Ernestinovo'
  | 'Kaptol'
  | 'Lepoglava'
  | 'Lukač'
  | 'Dicmo'
  | 'Grubišno Polje'
  | 'Klinča Sela'
  | 'Lekenik'
  | 'Supetar'
  | 'Baška'
  | 'Bilice'
  | 'Bjelovar'
  | 'Breznica'
  | 'Jasenovac'
  | 'Ludbreg'
  | 'Pazin'
  | 'Štitar'
  | 'Tar-Vabriga-Torre-Abrega'
  | 'Veliki Bukovec'
  | 'Kijevo'
  | 'Mljet'
  | 'Rešetari'
  | 'Veliko Trojstvo'
  | 'Crnac'
  | 'Molve'
  | 'Veliko Trgovišće'
  | 'Vinica'
  | 'Gračišće'
  | 'Stankovci'
  | 'Trpanj'
  | 'Vidovec'
  | 'Hrašćina'
  | 'Severin'
  | 'Pitomača'
  | 'Vodice'
  | 'Oroslavje'
